<?php

    class TContentGenerator extends TBaseGenerator
    {
        function render(array $attr = null, $innerText = null)
        {
            if (!isset($this->context)) return 'Content for content_id: '.$this->cms->idx_current_page.' not defined';
            $def = $this->context;

            $result = '';
            
            if (!isset($def->url)) 
            {
                $result = '<p>This is autogenerated based on defined content nodes</p>'."\n".'<q:list />';
                //return 'Content source reference missing for content_id: '.$this->cms->idx_current_page;
            }
            else 
            {            
                $filename = $def->url;
                if (!file_exists($filename)) return 'Content source not found for content_id: '.$this->cms->idx_current_page.' ('.$filename.')';
                
                $ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
                $result = file_get_contents($filename);
                
                switch ($ext)
                {
                    case 'txt':
                        $result = str_replace('[<', '::start::', $result);
                        $result = str_replace('>]', '::stop::', $result);
                        $result = htmlspecialchars($result, ENT_NOQUOTES);
                        $result = '<pre style="white-space: pre-wrap;">'.$result.'</pre>';
                        $result = str_replace('::start::', '<', $result);
                        $result = str_replace('::stop::', '>', $result);
                        return $result;
                    default:
                        return $result;
                        break;
                }
            }
            
            return $result;
        }
    }
    
?>